apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- name: munifiedworload.kb.io
  objectSelector:
    matchExpressions:
    - key: rollouts.kruise.io/unified-worload
      operator: Exists